### ISSUE TITLE
No ApiKey textbox in settings

### ISSUE THREAD

**Issue by marcoscale98** [dromara/ChatGPT#321]
Hi,

There isn't the OpenAI tab in the Settings as it says here https://chatgpt.en.obiscr.com/settings/openai-settings/#openai
And there isn't the API Key textbox
![immagine](https://github.com/user-attachments/assets/e579baf5-aa58-42c1-bd27-31e673e50798)

**Comment by obiscr** [comment]
@marcoscale98 The fact that we removed support for open api in the new 3.3.7 release means that only EasyCode AI can be used at this time. This document is deprecated, the latest one is: [https://chatgpt.gold](https://chatgpt.gold)

We apologise for not updating the documentation in a timely manner due to an oversight on our part.

**Comment by obiscr** [comment]
You can try to use EasyCode AI. if insist to use openai api. you can use version 3.3.6, in this version is supported open ai api. You can find the historical version here: https://plugins.jetbrains.com/plugin/20603-chatgpt--easycode/versions/stable
