### ISSUE TITLE
Cannot login using email and password if I signed up using gmail.

### ISSUE THREAD

**Issue by Vordead** [dromara/ChatGPT#98]

**Comment by obiscr** [comment]
At present, Open AI officially does not support Google/Microsoft account login, not because the plugin does not support it.

**Comment by CtrlAltFocus** [comment]
@obiscr 
Would you not be able to trigger it to open in our own browser? And share some key or token from the localStorage, or a cookie, or both?

Having to login with my account in your plugin's nested browser does not allow us to easily trust what is happening with our information.

**Comment by obiscr** [comment]
> Would you not be able to trigger it to open in our own browser? And share some key or token from the localStorage, or a cookie, or both?
I'm not sure if the current IntelliJ SDK supports doing this.

Regarding the privacy of account information. Your account information is not read within the plugin. 

> Having to login with my account in your plugin's nested browser does not allow us to easily trust what is happening with our information.

This is because there is a browser embedded. All the information is handled by the browser. The plugin is not going to read your account password information.
